### ISSUE TITLE
makefile error

### ISSUE THREAD

**Issue by darkoverlordofdata** [flyover/box2d.js#2]
when I run make, I get this error:
Box2D/Box2D/Dynamics/Joints/b2FrictionJoint.js:367: ERROR - Redeclared variable: Cdot
        var Cdot = box2d.b2Sub_V2_V2(
...
16 error(s), 0 warning(s)
They are all the same, redeclared variable.

**Comment by darkoverlordofdata** [comment]
Aha - I can compile with archived versions of the closure compiler. This error starts with the July release: July 29, 2015 (v20150729), probably this item on the release notes:

Aggressive variable checks are now on by default

Looks like it's found an old bug!

**Comment by flyover** [comment]
Thanks for the bug report.  I've relaxed the compiler flags so you can build, until I get these fixed up.

**Comment by darkoverlordofdata** [comment]
Verified it - that works. Thanks!
